import { GameMeta } from '@/types/game';

export const GAME_REGISTRY: GameMeta[] = [
  {
    id: 'balloon-match',
    title: 'Balloon Match',
    description:
      'Observe a balloon, then recreate it by feel. Test your memory and touch precision!',
    emoji: '🎈',
    gradientFrom: '#A855F7',
    gradientTo: '#EC4899',
    glowColor: 'rgba(168, 85, 247, 0.5)',
    isAvailable: true,
    href: '/games/balloon-match',
    tags: ['memory', 'precision', 'casual'],
  },
  {
    id: 'perfect-pour',
    title: 'Perfect Pour',
    description:
      'Watch a glass fill, then pour it back from memory. Calm, satisfying precision.',
    emoji: '🥤',
    gradientFrom: '#06B6D4',
    gradientTo: '#3B82F6',
    glowColor: 'rgba(6, 182, 212, 0.5)',
    isAvailable: true,
    href: '/games/perfect-pour',
    tags: ['memory', 'precision', 'relaxing'],
  },
  {
    id: 'memory-path',
    title: 'Memory Path',
    description:
      'A neon path lights up across the grid. Memorize it, then trace it back.',
    emoji: '🧠',
    gradientFrom: '#A855F7',
    gradientTo: '#06B6D4',
    glowColor: 'rgba(168, 85, 247, 0.5)',
    isAvailable: true,
    href: '/games/memory-path',
    tags: ['memory', 'focus', 'neon'],
  },
  {
    id: 'color-match',
    title: 'Color Match',
    description: 'Match the exact shade of a color. A visual memory challenge for designers.',
    emoji: '🎨',
    gradientFrom: '#F472B6',
    gradientTo: '#8B5CF6',
    glowColor: 'rgba(244, 114, 182, 0.5)',
    isAvailable: false,
    href: '/games/color-match',
    tags: ['memory', 'visual', 'color'],
  },
  {
    id: 'rhythm-tap',
    title: 'Rhythm Tap',
    description: 'Tap to the beat! Follow the rhythm and keep perfect timing.',
    emoji: '🥁',
    gradientFrom: '#22C55E',
    gradientTo: '#14B8A6',
    glowColor: 'rgba(34, 197, 94, 0.5)',
    isAvailable: false,
    href: '/games/rhythm-tap',
    tags: ['rhythm', 'music', 'timing'],
  },
  {
    id: 'number-rush',
    title: 'Number Rush',
    description: 'Count and tap numbers in sequence as fast as you can. Train your focus!',
    emoji: '🔢',
    gradientFrom: '#F97316',
    gradientTo: '#EF4444',
    glowColor: 'rgba(249, 115, 22, 0.5)',
    isAvailable: false,
    href: '/games/number-rush',
    tags: ['speed', 'focus', 'numbers'],
  },
  {
    id: 'word-burst',
    title: 'Word Burst',
    description: 'Find hidden words before time runs out. Speed and vocabulary combined!',
    emoji: '💬',
    gradientFrom: '#EAB308',
    gradientTo: '#F97316',
    glowColor: 'rgba(234, 179, 8, 0.5)',
    isAvailable: false,
    href: '/games/word-burst',
    tags: ['word', 'speed', 'vocabulary'],
  },
  {
    id: 'shape-stack',
    title: 'Shape Stack',
    description: 'Stack falling shapes perfectly. Physics-based stacking madness!',
    emoji: '🔷',
    gradientFrom: '#8B5CF6',
    gradientTo: '#06B6D4',
    glowColor: 'rgba(139, 92, 246, 0.5)',
    isAvailable: false,
    href: '/games/shape-stack',
    tags: ['physics', 'skill', 'casual'],
  },
];
